(function(){
'use strict';
var HW=['Refurbished Laptop','Custom Desktop','GPU Workbench','Mining Rack','Liquid Cooled Array','Private Server Room','Modular Data Centre','Renewable Compute Farm','Quantum Processor','Ocean Cooled Facility','Lunar Compute Vault','Orbital Processing Ring','Edge Compute Pod','Photonics Bench','AI Accelerator Cluster','Cryogenic Core','Solar Compute Field','Autonomous Rack Swarm','Neural Fabric Hub','Fusion Powered Campus','Deep Sea Node','Lunar Relay Grid','Mars Data Foundry','Orbital Quantum Mesh'];
var TOK=['Spark','Nova','Pulse','Orbit','Flux','Aether','Prism','Volt','Helix','Quanta','Zenith','Lumen','Echo','Vanta','Nexus','Solaris','Cipher','Nebula','Titan','Singularity'];
var LOC=['Rented Garage','Converted Warehouse','Rooftop Technology Lab','Coastal Innovation Campus','Metropolitan Tower','Alpine Server Vault','Ocean Research City','Lunar Compute Base','Mars Technology Colony','Orbital Processing Ring'];
var BLUE=['Copper Cooling Plan','Cobalt Routing Plan','Neon Power Plan','Titan Security Plan','Quantum Automation Plan','Copper Optics Plan','Cobalt Cooling Plan','Neon Routing Plan','Titan Power Plan','Quantum Security Plan','Copper Automation Plan','Cobalt Optics Plan'];
var KEY='hash-empire-safe-v3';
function fresh(){return{cash:25,life:25,tap:0,token:0,hw:Array(HW.length).fill(0),legacy:0,chips:0,loc:0,last:Date.now(),blue:[],settings:{sound:true,vibration:true,motion:true}}}
var s=fresh();try{var old=JSON.parse(localStorage.getItem(KEY)||'null');if(old){Object.assign(s,old);s.settings=Object.assign(fresh().settings,old.settings||{});s.hw=Array.from({length:HW.length},function(_,i){return Number(old.hw&&old.hw[i]||0)})}}catch(e){}
var tab='Empire',qty=1,combo=1,lastTap=0,canvas,ctx,raf,sceneTime=0,audio;
function fmt(n){n=Number(n);if(!isFinite(n))return '∞';if(n<1e3)return n.toLocaleString(undefined,{maximumFractionDigits:n<100?1:0});if(n<1e6)return (n/1e3).toFixed(n<1e4?1:0)+'K';var u=['M','B','T','Qa','Qi','Sx','Sp','Oc','No','Dc'],i=Math.min(u.length-1,Math.floor(Math.log10(n)/3)-2);return (n/Math.pow(1000,i+2)).toFixed(n<1e8?1:2)+u[i]}
function mile(q){return [10,25,50,100,250,500].reduce(function(m,x){return q>=x?m*2:m},1)}
function income(){return HW.reduce(function(total,_,i){return total+(1.5*Math.pow(7.2,i))*(Number(s.hw[i])||0)*mile(Number(s.hw[i])||0)},0)*(1+s.legacy*.1)}
function baseTap(){return Math.pow(4.2,s.token)*(1+s.tap*.65)*(1+s.legacy*.1)}
function tapVal(){return baseTap()*combo}
function tapCost(c){c=c||1;return 25*Math.pow(1.55,s.tap)*(Math.pow(1.55,c)-1)/.55}
function unitCost(i,o){return 10*Math.pow(8,i)*Math.pow(1.15,typeof o==='undefined'?s.hw[i]:o)}
function batch(i,c){return unitCost(i)*(Math.pow(1.15,c)-1)/.15}
function maxBuy(i){var c=0,total=0;while(c<999&&total+unitCost(i,s.hw[i]+c)<=s.cash){total+=unitCost(i,s.hw[i]+c);c++}return c}
function worldCost(){return s.loc>=LOC.length-1?Infinity:Math.pow(1e4,s.loc+1)}
function progress(){return Math.min(100,s.cash/worldCost()*100)}
function save(){s.last=Date.now();try{localStorage.setItem(KEY,JSON.stringify(s))}catch(e){}}
function iconFor(i){return ['⌁','▱','GPU','▦','◫','SRV','DC','☼','Q','OC','LV','OR'][i%12]}
function nav(){var a=[['Empire','H'],['Hardware','▦'],['Tokens','◉'],['Influence','✦'],['Legacy','◇']];return '<nav class="bottom-nav">'+a.map(function(x){return '<button data-tab="'+x[0]+'" class="'+(tab===x[0]?'active':'')+'"><span>'+x[1]+'</span>'+x[0]+'</button>'}).join('')+'</nav>'}
function hud(){return '<header class="hud"><div class="brand"><div class="brand-mark">H</div><div class="brand-copy"><b>HASH EMPIRE</b><small>IDLE TECH TYCOON</small></div></div><div class="wealth"><label>NET WORTH</label><strong id="cash">£'+fmt(s.cash)+'</strong><span id="income">+£'+fmt(income())+' / sec</span></div></header>'}
function stage(){var next=s.loc<LOC.length-1?LOC[s.loc+1]:'Empire complete';return '<section class="stage"><canvas id="world" class="world-canvas"></canvas><div class="stage-top"><div class="location"><div class="location-pin">⌖</div><div><small>OPERATION 0'+(s.loc+1)+'</small><b>'+LOC[s.loc]+'</b></div></div><div class="chips">◈ '+s.chips+'</div></div><div class="core-wrap"><div class="core-aura"></div><div class="core-ring"></div><button id="mine" class="mine-core" aria-label="Generate hash"><b>'+TOK[s.token].charAt(0)+'</b></button><span class="tap-label">TAP TO GENERATE</span><div id="combo" class="combo-pill '+(combo>=5?'hot':'')+'">x'+combo.toFixed(1)+'</div></div><div class="mission"><div class="mission-icon">↗</div><div class="mission-copy"><small>NEXT EXPANSION</small><b>'+next+'</b><div class="bar"><i id="progress" style="width:'+progress()+'%"></i></div></div><em id="worldcost">'+(isFinite(worldCost())?'£'+fmt(worldCost()):'MAX')+'</em></div></section>'}
function empire(){return stage()+'<section class="dashboard"><div class="stat-strip"><div class="stat"><small>TAP OUTPUT</small><b id="tapstat">£'+fmt(baseTap())+'</b></div><div class="stat"><small>COMBO</small><b id="combostat" class="cyan">x'+combo.toFixed(1)+'</b></div><div class="stat"><small>LEGACY BOOST</small><b>x'+(1+s.legacy*.1).toFixed(1)+'</b></div></div><div class="primary-actions"><button id="upTap" class="action" '+(s.cash<tapCost(1)?'disabled':'')+'><span class="action-icon">↑</span><small>BOOST OUTPUT</small><b>Upgrade, £'+fmt(tapCost(1))+'</b></button><button id="expand" class="action gold" '+(s.cash<worldCost()||!isFinite(worldCost())?'disabled':'')+'><span class="action-icon">⌖</span><small>NEXT LOCATION</small><b>'+(isFinite(worldCost())?'Expand, £'+fmt(worldCost()):'World complete')+'</b></button></div></section>'}
function head(kicker,title,desc,badge){return '<div class="view-head"><div><small>'+kicker+'</small><h1>'+title+'</h1><p>'+desc+'</p></div>'+(badge?'<span class="section-badge">'+badge+'</span>':'')+'</div>'}
function hardware(){var qs=[1,10,25,'MAX'],out='<section class="view">'+head('BUILD THE MACHINE','Hardware','Every asset keeps earning while you are away',s.hw.reduce(function(a,b){return a+b},0)+' ASSETS')+'<div class="seg">'+qs.map(function(q){return '<button data-qty="'+q+'" class="'+(qty==q?'on':'')+'">'+q+'</button>'}).join('')+'</div>';HW.forEach(function(name,i){var c=qty==='MAX'?maxBuy(i):qty,cost=batch(i,Math.max(1,c)),lock=s.life<Math.pow(7,i)*35,owned=s.hw[i],rate=1.5*Math.pow(7.2,i)*owned*mile(owned);out+='<article class="card '+(lock?'locked':'')+'"><div class="item-icon">'+iconFor(i)+'</div><div class="card-copy"><h3>'+name+'</h3><p>'+owned+' owned, £'+fmt(rate)+'/sec</p><div class="meta"><span>'+(['Fast return','Balanced yield','Long term'][i%3])+'</span><i></i><span>Tier '+(Math.floor(i/6)+1)+'</span></div></div><button class="buy" data-buy="'+i+'" '+(lock||c<1||s.cash<cost?'disabled':'')+'>'+(lock?'LOCKED':'BUY '+c)+'<br><b>£'+fmt(cost)+'</b></button></article>'});return out+'</section>'}
function tokens(){var out='<section class="view">'+head('OUTPUT PROTOCOL','Hash Tokens','Upgrade the core at the heart of your network',(s.tap+1)+' LEVEL')+'<div class="hero-card"><small>ACTIVE CORE</small><h2>'+TOK[s.token]+' Protocol</h2><p>Every tap currently generates £'+fmt(baseTap())+'. Reach level '+((s.token+1)*5)+' to unlock the next protocol.</p><button id="buy10" '+(s.cash<tapCost(10)?'disabled':'')+'>INSTALL 10 UPGRADES, £'+fmt(tapCost(10))+'</button></div>';TOK.forEach(function(name,i){var lock=s.tap<i*5;out+='<article class="card '+(lock?'locked':'')+'"><div class="item-icon gold">'+name.charAt(0)+'</div><div class="card-copy"><h3>'+name+' Protocol</h3><p>+'+(2+i)+'% '+(i%2?'hardware':'tap')+' performance</p><div class="meta"><span>'+(lock?'Unlocks at level '+i*5:i===s.token?'Active core':'Protocol unlocked')+'</span></div></div>'+(i===s.token?'<span class="section-badge">ACTIVE</span>':'')+'</article>'});return out+'</section>'}
function influence(){var jobs=[['Launch the Signal Podcast','Attention converts into stronger tap streaks'],['Release Open Source Tools','Community contributors optimise your hardware'],['Sponsor an Esports Team','Global recognition increases all revenue'],['Host the Future Summit','Industry leaders accelerate expansion'],['Fund the Creator Network','Permanent audience growth across every run'],['Establish a Research Lab','Frontier technology compounds your output']];var out='<section class="view">'+head('TURN REACH INTO POWER','Influence','Build a public empire as well as a technical one','CHAPTER 1');jobs.forEach(function(x,i){var cost=Math.pow(10,4+i*2.5),lock=s.life<cost/2;out+='<article class="card '+(lock?'locked':'')+'"><div class="item-icon">'+String(i+1).padStart(2,'0')+'</div><div class="card-copy"><h3>'+x[0]+'</h3><p>'+x[1]+'</p><div class="meta"><span>Permanent +'+(5+i*3)+'% boost</span></div></div><button class="buy" data-fund="'+i+'" '+(lock||s.cash<cost?'disabled':'')+'>FUND<br><b>£'+fmt(cost)+'</b></button></article>'});return out+'</section>'}
function legacy(){var pts=Math.floor(Math.pow(s.life/1e9,.25)),out='<section class="view">'+head('THE END IS THE BEGINNING','Legacy','Sell the empire, keep the knowledge, build faster','x'+(1+s.legacy*.1).toFixed(1))+'<div class="hero-card"><small>EXIT OPPORTUNITY</small><h2>'+pts+' Legacy Point'+(pts===1?'':'s')+'</h2><p>Relaunching resets cash, locations, hardware and tap upgrades. Your Legacy multiplier and collected blueprints remain forever.</p><button id="prestige" '+(pts<1?'disabled':'')+'>'+(pts<1?'REACH £1B LIFETIME TO UNLOCK':'REVIEW EXIT AND RELAUNCH')+'</button></div>'+head('PERMANENT COLLECTION','Blueprints','Rare plans survive every relaunch',s.blue.length+'/30');BLUE.forEach(function(name,i){var owned=s.blue.indexOf(i)>-1;out+='<article class="card '+(!owned?'locked':'')+'"><div class="item-icon">'+(i+1)+'</div><div class="card-copy"><h3>'+name+'</h3><p>'+(['Common','Rare','Epic','Legendary'][Math.min(3,Math.floor(i/4))])+', x'+(1.03+i*.01).toFixed(2)+' '+(['personal','rack','facility','frontier'][i%4])+'</p><div class="meta"><span>'+(owned?'Collected':'Earn from milestones and events')+'</span></div></div></article>'});out+='<div class="setting-list"><div class="setting"><span>Sound effects</span><button class="toggle '+(s.settings.sound?'on':'')+'" data-setting="sound"></button></div><div class="setting"><span>Haptic feedback</span><button class="toggle '+(s.settings.vibration?'on':'')+'" data-setting="vibration"></button></div><button id="reset" class="wide-button danger">RESET GAME DATA</button></div></section>';return out}
function screen(){if(tab==='Empire')return empire();if(tab==='Hardware')return hardware();if(tab==='Tokens')return tokens();if(tab==='Influence')return influence();return legacy()}
function render(){cancelAnimationFrame(raf);document.getElementById('app').innerHTML='<main class="shell">'+hud()+screen()+nav()+'</main>';bind();if(tab==='Empire')startScene()}
function bind(){document.querySelectorAll('[data-tab]').forEach(function(el){el.onclick=function(){tab=el.dataset.tab;render()}});document.querySelectorAll('[data-qty]').forEach(function(el){el.onclick=function(){qty=el.dataset.qty==='MAX'?'MAX':Number(el.dataset.qty);render()}});document.querySelectorAll('[data-buy]').forEach(function(el){el.onclick=function(){var i=Number(el.dataset.buy),c=qty==='MAX'?maxBuy(i):qty,cost=batch(i,c);if(c&&s.cash>=cost){s.cash-=cost;s.hw[i]+=c;ping(240);save();render();toast('Hardware installed, +£'+fmt(1.5*Math.pow(7.2,i)*c)+'/sec')}}});document.querySelectorAll('[data-fund]').forEach(function(el){el.onclick=function(){var i=Number(el.dataset.fund),cost=Math.pow(10,4+i*2.5);if(s.cash>=cost){s.cash-=cost;save();render();toast('Influence project funded')}}});document.querySelectorAll('[data-setting]').forEach(function(el){el.onclick=function(){var k=el.dataset.setting;s.settings[k]=!s.settings[k];save();render()}});var mine=document.getElementById('mine');if(mine)mine.onpointerdown=doTap;var u=document.getElementById('upTap');if(u)u.onclick=function(){var c=tapCost(1);if(s.cash>=c){s.cash-=c;s.tap++;s.token=Math.min(TOK.length-1,Math.floor(s.tap/5));ping(420);save();render();toast('Output boosted to £'+fmt(baseTap())+' per tap')}};var b=document.getElementById('buy10');if(b)b.onclick=function(){var c=tapCost(10);if(s.cash>=c){s.cash-=c;s.tap+=10;s.token=Math.min(TOK.length-1,Math.floor(s.tap/5));ping(520);save();render()}};var ex=document.getElementById('expand');if(ex)ex.onclick=function(){var c=worldCost();if(s.cash>=c&&isFinite(c)){s.cash-=c;s.loc++;ping(620);save();render();toast('New operation opened, '+LOC[s.loc])}};var p=document.getElementById('prestige');if(p)p.onclick=prestige;var r=document.getElementById('reset');if(r)r.onclick=function(){if(confirm('Reset all Hash Empire progress? This cannot be undone.')){s=fresh();save();render()}}}
function doTap(e){e.preventDefault();var now=Date.now();combo=now-lastTap<520?Math.min(8,combo+.22):Math.max(1,combo);lastTap=now;var v=tapVal();s.cash+=v;s.life+=v;s.token=Math.min(TOK.length-1,Math.floor(s.tap/5));if(s.settings.vibration&&navigator.vibrate)navigator.vibrate(combo>5?14:7);ping(170+combo*16);var core=document.getElementById('mine');core.classList.add('hit');setTimeout(function(){core&&core.classList.remove('hit')},80);floater(e.clientX,e.clientY,'+£'+fmt(v));sparks(core);updateHud()}
function updateHud(){var el=document.getElementById('cash');if(el)el.textContent='£'+fmt(s.cash);el=document.getElementById('income');if(el)el.textContent='+£'+fmt(income())+' / sec';el=document.getElementById('combo');if(el){el.textContent='x'+combo.toFixed(1);el.className='combo-pill '+(combo>=5?'hot':'')}el=document.getElementById('combostat');if(el)el.textContent='x'+combo.toFixed(1);el=document.getElementById('tapstat');if(el)el.textContent='£'+fmt(baseTap());el=document.getElementById('progress');if(el)el.style.width=progress()+'%'}
function floater(x,y,text){var f=document.createElement('i');f.className='floater';f.style.left=(x-20)+'px';f.style.top=(y-15)+'px';f.textContent=text;document.body.appendChild(f);setTimeout(function(){f.remove()},850)}
function sparks(core){if(!core||!s.settings.motion)return;var box=core.getBoundingClientRect();for(var i=0;i<7;i++){var p=document.createElement('i'),a=Math.random()*Math.PI*2,d=35+Math.random()*55;p.className='spark';p.style.left=(box.left+box.width/2)+'px';p.style.top=(box.top+box.height/2)+'px';p.style.setProperty('--dx',Math.cos(a)*d+'px');p.style.setProperty('--dy',Math.sin(a)*d+'px');document.body.appendChild(p);setTimeout(function(x){return function(){x.remove()}}(p),650)}}
function toast(text){var t=document.createElement('div');t.className='toast';t.textContent=text;document.body.appendChild(t);setTimeout(function(){t.remove()},2400)}
function ping(freq){if(!s.settings.sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();var o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*1.35,audio.currentTime+.06);g.gain.setValueAtTime(.025,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.08);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.08)}catch(e){}}
function prestige(){var pts=Math.floor(Math.pow(s.life/1e9,.25));if(pts<1)return;if(confirm('Exit this run for '+pts+' Legacy Point'+(pts===1?'':'s')+'? Cash, hardware, locations and tap upgrades will reset.')){var keep=s.legacy+pts,blue=s.blue,chips=s.chips,settings=s.settings;s=fresh();s.legacy=keep;s.blue=blue;s.chips=chips;s.settings=settings;save();render()}}
function startScene(){canvas=document.getElementById('world');if(!canvas)return;ctx=canvas.getContext('2d');sceneTime=0;drawScene()}
function drawScene(){if(!canvas||!document.body.contains(canvas))return;var d=Math.min(window.devicePixelRatio||1,2),w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==Math.round(w*d)||canvas.height!==Math.round(h*d)){canvas.width=Math.round(w*d);canvas.height=Math.round(h*d)}ctx.setTransform(d,0,0,d,0,0);sceneTime+=.012;var sky=ctx.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#071321');sky.addColorStop(.55,'#101927');sky.addColorStop(1,'#05070c');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);
// rear wall and ceiling
ctx.fillStyle='#111a25';ctx.fillRect(0,0,w,h*.62);ctx.strokeStyle='#243341';ctx.lineWidth=1;for(var x=0;x<w;x+=64){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h*.62);ctx.stroke()}for(var y=40;y<h*.62;y+=52){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}
// cyan tube lights
ctx.shadowBlur=18;ctx.shadowColor='#4ce9e2';ctx.fillStyle='#78fff5';ctx.fillRect(w*.12,68,w*.19,3);ctx.fillRect(w*.69,68,w*.19,3);ctx.shadowBlur=0;ctx.fillStyle='#55e8df22';ctx.fillRect(w*.08,70,w*.27,h*.5);
// left desk and monitor
ctx.fillStyle='#080c12';ctx.fillRect(w*.05,h*.38,w*.28,h*.04);ctx.fillStyle='#172431';ctx.fillRect(w*.09,h*.25,w*.18,h*.13);ctx.strokeStyle='#3d6870';ctx.strokeRect(w*.09,h*.25,w*.18,h*.13);var mg=ctx.createLinearGradient(w*.1,h*.26,w*.25,h*.37);mg.addColorStop(0,'#1d5871');mg.addColorStop(1,'#12143c');ctx.fillStyle=mg;ctx.fillRect(w*.105,h*.265,w*.15,h*.095);ctx.strokeStyle='#64e9df80';for(var l=0;l<4;l++){ctx.beginPath();ctx.moveTo(w*.115,h*(.33-l*.012));ctx.lineTo(w*(.14+l*.025),h*(.29+l*.006));ctx.lineTo(w*(.18+l*.018),h*(.315-l*.008));ctx.lineTo(w*.245,h*(.28+l*.012));ctx.stroke()}ctx.fillStyle='#15202a';ctx.fillRect(w*.16,h*.38,4,h*.18);ctx.fillRect(w*.27,h*.38,4,h*.18);
// right server racks, count reflects ownership
var racks=Math.max(1,Math.min(4,s.hw.filter(function(v){return v>0}).length));for(var r=0;r<racks;r++){var rx=w-(r+1)*56;ctx.fillStyle='#0b1018';ctx.fillRect(rx,h*.2,45,h*.39);ctx.strokeStyle='#334858';ctx.strokeRect(rx,h*.2,45,h*.39);for(var q=0;q<6;q++){ctx.fillStyle='#182735';ctx.fillRect(rx+5,h*.23+q*24,35,16);ctx.fillStyle=(Math.sin(sceneTime*5+q+r)>0?'#50ebd8':'#277f79');ctx.fillRect(rx+9,h*.26+q*24,3,2);ctx.fillStyle='#785bff';ctx.fillRect(rx+15,h*.26+q*24,2,2)}}
// floor perspective
ctx.fillStyle='#070b11';ctx.fillRect(0,h*.59,w,h*.41);ctx.strokeStyle='#263547';for(var px=-w;px<w*2;px+=52){ctx.beginPath();ctx.moveTo(w/2,h*.59);ctx.lineTo(px,h);ctx.stroke()}for(var py=h*.64;py<h;py+=38){ctx.beginPath();ctx.moveTo(0,py);ctx.lineTo(w,py);ctx.stroke()}
// centre cable glow
var glow=ctx.createRadialGradient(w/2,h*.72,4,w/2,h*.72,w*.28);glow.addColorStop(0,'#38e5d526');glow.addColorStop(1,'transparent');ctx.fillStyle=glow;ctx.fillRect(0,h*.48,w,h*.52);
// dust motes
for(var m=0;m<18;m++){var mx=(m*83+sceneTime*22*(m%3+1))%(w+20)-10,my=(m*47+Math.sin(sceneTime+m)*14)%(h*.65);ctx.globalAlpha=.15+(m%4)*.06;ctx.fillStyle=m%3?'#bde6ef':'#5ff1e5';ctx.fillRect(mx,my,1.3,1.3)}ctx.globalAlpha=1;raf=requestAnimationFrame(drawScene)}
function offline(){var secs=Math.max(0,Math.min((Date.now()-Number(s.last||Date.now()))/1000,14400)),reward=income()*secs*.5;if(secs<20||reward<=0){s.last=Date.now();save();render();return}s.cash+=reward;s.life+=reward;s.last=Date.now();save();render();var m=document.createElement('div');m.className='modal';m.innerHTML='<div class="modal-box"><div class="modal-mark">H</div><h2>Your empire stayed online</h2><p>The network kept generating while you were away, at 50% offline efficiency.</p><div class="reward"><small>OFFLINE REVENUE</small><b>£'+fmt(reward)+'</b></div><button class="wide-button" id="collect">COLLECT AND CONTINUE</button></div>';document.body.appendChild(m);m.querySelector('#collect').onclick=function(){ping(480);m.remove()}}
setInterval(function(){var inc=income()/5;s.cash+=inc;s.life+=inc;if(Date.now()-lastTap>2200)combo=Math.max(1,combo-.08);updateHud()},200);setInterval(save,5000);offline();
})();
