(function(){
'use strict';
var HW=['Refurbished Laptop','Custom Desktop','GPU Workbench','Mining Rack','Liquid Cooled Array','Private Server Room','Modular Data Centre','Renewable Compute Farm','Quantum Processor','Ocean Cooled Facility','Lunar Compute Vault','Orbital Processing Ring','Edge Compute Pod','Photonics Bench','AI Accelerator Cluster','Cryogenic Core','Solar Compute Field','Autonomous Rack Swarm','Neural Fabric Hub','Fusion Powered Campus','Deep Sea Node','Lunar Relay Grid','Mars Data Foundry','Orbital Quantum Mesh'];
var TOK=['Spark','Nova','Pulse','Orbit','Flux','Aether','Prism','Volt','Helix','Quanta','Zenith','Lumen','Echo','Vanta','Nexus','Solaris','Cipher','Nebula','Titan','Singularity'];
var LOC=['Rented Garage','Converted Warehouse','Rooftop Technology Lab','Coastal Innovation Campus','Metropolitan Tower','Alpine Server Vault','Ocean Research City','Lunar Compute Base','Mars Technology Colony','Orbital Processing Ring'];
var BLUE=['Copper Cooling Plan','Cobalt Routing Plan','Neon Power Plan','Titan Security Plan','Quantum Automation Plan','Copper Optics Plan','Cobalt Cooling Plan','Neon Routing Plan','Titan Power Plan','Quantum Security Plan','Copper Automation Plan','Cobalt Optics Plan'];
var HW_COST=[10,120,1400,16000,180000,2000000],HW_INCOME=[1.2,9,72,580,4700,38000];
var MISSIONS=[
 {title:'Wake the machine',copy:'Generate 5 manual hashes',kind:'taps',target:5,reward:25},
 {title:'Increase the output',copy:'Install your first tap upgrade',kind:'tap',target:1,reward:45},
 {title:'Start earning offline',copy:'Buy a Refurbished Laptop',kind:'hw0',target:1,reward:80},
 {title:'Build the first fleet',copy:'Own 10 Refurbished Laptops',kind:'hw0',target:10,reward:300},
 {title:'Move beyond the laptop',copy:'Own 3 Custom Desktops',kind:'hw1',target:3,reward:750},
 {title:'Find a faster protocol',copy:'Reach tap level 5',kind:'tap',target:5,reward:1800},
 {title:'Create real momentum',copy:'Generate £500 per second',kind:'income',target:500,reward:5000},
 {title:'Prepare to expand',copy:'Build a network of 30 assets',kind:'assets',target:30,reward:12000},
 {title:'Leave the garage',copy:'Open the Converted Warehouse',kind:'location',target:1,reward:25000}
];
var KEY='hash-empire-safe-v3';
function fresh(){return{cash:25,life:25,tap:0,taps:0,token:0,hw:Array(HW.length).fill(0),legacy:0,chips:0,loc:0,last:Date.now(),blue:[],influence:[],mission:0,tutorial:0,milestones:[],settings:{sound:true,vibration:true,motion:true}}}
var s=fresh();try{var old=JSON.parse(localStorage.getItem(KEY)||'null');if(old){Object.assign(s,old);s.settings=Object.assign(fresh().settings,old.settings||{});s.hw=Array.from({length:HW.length},function(_,i){return Number(old.hw&& old.hw[i]||0)});s.milestones=Array.isArray(old.milestones)?old.milestones:[];s.influence=Array.isArray(old.influence)?old.influence:[];if(typeof old.tutorial==='undefined'&&Number(old.life||25)>25)s.tutorial=5}}catch(e){}
var tab='Empire',qty=1,combo=1,lastTap=0,overclockUntil=0,canvas,ctx,raf,sceneTime=0,audio;
function fmt(n){n=Number(n);if(!isFinite(n))return '∞';if(n<1e3)return n.toLocaleString(undefined,{maximumFractionDigits:n<100?1:0});if(n<1e6)return (n/1e3).toFixed(n<1e4?1:0)+'K';var u=['M','B','T','Qa','Qi','Sx','Sp','Oc','No','Dc'],i=Math.min(u.length-1,Math.floor(Math.log10(n)/3)-2);return (n/Math.pow(1000,i+2)).toFixed(n<1e8?1:2)+u[i]}
function mile(q){return [10,25,50,100,250,500].reduce(function(m,x){return q>=x?m*2:m},1)}
function hwCost(i){return i<HW_COST.length?HW_COST[i]:HW_COST[5]*Math.pow(8,i-5)}
function hwIncome(i){return i<HW_INCOME.length?HW_INCOME[i]:HW_INCOME[5]*Math.pow(7.4,i-5)}
function influenceBoost(){return 1+(s.influence||[]).reduce(function(sum,i){return sum+(5+i*3)/100},0)}
function income(){return HW.reduce(function(total,_,i){return total+hwIncome(i)*(Number(s.hw[i])||0)*mile(Number(s.hw[i])||0)},0)*(1+s.legacy*.1)*influenceBoost()}
function baseTap(){return Math.pow(4.2,s.token)*(1+s.tap*.72)*(1+s.legacy*.1)*influenceBoost()}
function tapVal(){return baseTap()*combo*(Date.now()<overclockUntil?2:1)}
function tapCost(c){c=c||1;return 25*Math.pow(1.42,s.tap)*(Math.pow(1.42,c)-1)/.42}
function unitCost(i,o){return hwCost(i)*Math.pow(1.15,typeof o==='undefined'?s.hw[i]:o)}
function batch(i,c){return unitCost(i)*(Math.pow(1.15,c)-1)/.15}
function maxBuy(i){var c=0,total=0;while(c<999&&total+unitCost(i,s.hw[i]+c)<=s.cash){total+=unitCost(i,s.hw[i]+c);c++}return c}
function worldCost(){return s.loc>=LOC.length-1?Infinity:Math.pow(1e4,s.loc+1)}
function progress(){return Math.min(100,s.cash/worldCost()*100)}
function missionValue(m){if(!m)return 1;if(m.kind==='taps')return s.taps||0;if(m.kind==='tap')return s.tap;if(m.kind==='income')return income();if(m.kind==='assets')return s.hw.reduce(function(a,b){return a+b},0);if(m.kind==='location')return s.loc;if(m.kind.indexOf('hw')===0)return s.hw[Number(m.kind.slice(2))]||0;return 0}
function activeMission(){return MISSIONS[Math.min(s.mission||0,MISSIONS.length-1)]}
function missionDone(){var m=activeMission();return (s.mission||0)>=MISSIONS.length||missionValue(m)>=m.target}
function missionPct(){var m=activeMission();return Math.min(100,missionValue(m)/m.target*100)}
function save(){s.last=Date.now();try{localStorage.setItem(KEY,JSON.stringify(s))}catch(e){}}
function iconFor(i){return ['⌁','▱','GPU','▦','◫','SRV','DC','☼','Q','OC','LV','OR'][i%12]}
function nav(){var a=[['Empire','H'],['Hardware','▦'],['Tokens','◉'],['Influence','✦'],['Legacy','◇']];return '<nav class="bottom-nav">'+a.map(function(x){return '<button data-tab="'+x[0]+'" class="'+(tab===x[0]?'active':'')+'"><span>'+x[1]+'</span>'+x[0]+'</button>'}).join('')+'</nav>'}
function hud(){return '<header class="hud"><div class="brand"><div class="brand-mark">H</div><div class="brand-copy"><b>HASH EMPIRE</b><small>IDLE TECH TYCOON</small></div></div><div class="wealth"><label>NET WORTH</label><strong id="cash">£'+fmt(s.cash)+'</strong><span id="income">+£'+fmt(income())+' / sec</span></div></header>'}
function aiLine(){var lines=['That laptop sounds like a hoover, but it works.','Every tap is technically a business strategy.','Passive income first. Sleep eventually.','Ten laptops. The extension lead is terrified.','Desktops online. We are almost respectable.','New protocol detected. Try not to look smug.','The electricity bill has entered the chat.','Thirty machines. The garage has become sentient.','We need more space before the landlord visits.'];return lines[Math.min(lines.length-1,s.mission||0)]}
function sceneEquipment(){var assets=s.hw.reduce(function(a,b){return a+b},0),out='<div class="scene-equipment">';if((s.hw[0]||0)>0)out+='<div class="prop laptop-prop"><i></i><b>'+Math.min(99,s.hw[0])+'</b></div>';if((s.hw[1]||0)>0)out+='<div class="prop desktop-prop"><i></i><i></i><b>'+Math.min(99,s.hw[1])+'</b></div>';if((s.hw[2]||0)>0)out+='<div class="prop gpu-prop"><i></i><i></i><i></i><b>'+Math.min(99,s.hw[2])+'</b></div>';if(assets>=10)out+='<div class="power-cable"></div>';return out+'</div>'}
function stage(){var m=activeMission(),complete=(s.mission||0)>=MISSIONS.length,done=!complete&&missionDone(),label=complete?'Chapter complete':m.title,detail=complete?'The garage operation is established':m.copy;return '<section id="stage" class="stage '+(s.loc===0?'art-stage':'')+'">'+(s.loc===0?'<img class="scene-art" src="assets/garage-night.webp?v=visual-4" alt="The Hash Empire garage at night"><div class="rain-layer"></div><div class="window-flash"></div>'+sceneEquipment()+'<button id="aiBubble" class="ai-bubble"><small>NOVA AI</small><span>'+aiLine()+'</span></button>':'')+'<canvas id="world" class="world-canvas"></canvas><div class="stage-top"><div class="location"><div class="location-pin">⌖</div><div><small>OPERATION 0'+(s.loc+1)+'</small><b>'+LOC[s.loc]+'</b></div></div><div class="chips">◈ '+s.chips+'</div></div><div class="core-wrap"><div class="core-aura"></div><div class="core-ring"></div><button id="mine" class="mine-core" aria-label="Generate hash"><b>'+TOK[s.token].charAt(0)+'</b></button><span class="tap-label">TAP TO GENERATE</span><div class="power-meter"><i id="powerbar" style="width:'+Math.min(100,combo/8*100)+'%"></i></div><div id="combo" class="combo-pill '+(combo>=5?'hot':'')+'">x'+combo.toFixed(1)+'</div></div><button id="claimMission" class="mission '+(done?'ready':'')+'" '+(done?'':'disabled')+'><div class="mission-icon">'+(done?'✓':'↗')+'</div><div class="mission-copy"><small>'+(done?'MISSION COMPLETE':'CURRENT MISSION')+'</small><b>'+label+'</b><span>'+detail+'</span><div class="bar"><i id="missionbar" style="width:'+(complete?100:missionPct())+'%"></i></div></div><em>'+(done?'CLAIM':complete?'DONE':'£'+fmt(m.reward))+'</em></button></section>'}
function empire(){return stage()+'<section class="dashboard"><div class="stat-strip"><div class="stat"><small>TAP OUTPUT</small><b id="tapstat">£'+fmt(baseTap())+'</b></div><div class="stat"><small>COMBO</small><b id="combostat" class="cyan">x'+combo.toFixed(1)+'</b></div><div class="stat"><small>LEGACY BOOST</small><b>x'+(1+s.legacy*.1).toFixed(1)+'</b></div></div><div class="primary-actions"><button id="upTap" class="action" '+(s.cash<tapCost(1)?'disabled':'')+'><span class="action-icon">↑</span><small>BOOST OUTPUT</small><b>Upgrade, £'+fmt(tapCost(1))+'</b></button><button id="expand" class="action gold" '+(s.cash<worldCost()||!isFinite(worldCost())?'disabled':'')+'><span class="action-icon">⌖</span><small>NEXT LOCATION</small><b>'+(isFinite(worldCost())?'Expand, £'+fmt(worldCost()):'World complete')+'</b></button></div></section>'}
function head(kicker,title,desc,badge){return '<div class="view-head"><div><small>'+kicker+'</small><h1>'+title+'</h1><p>'+desc+'</p></div>'+(badge?'<span class="section-badge">'+badge+'</span>':'')+'</div>'}
function hardware(){var qs=[1,10,25,'MAX'],assets=s.hw.reduce(function(a,b){return a+b},0),out='<section class="view hardware-view"><div class="operations-hero"><div class="operations-copy"><small>LIVE OPERATIONS FLOOR</small><h1>'+assets+' connected assets</h1><p>Your machines are generating <b>£'+fmt(income())+'</b> every second.</p><div class="ops-metrics"><span><i></i> NETWORK ONLINE</span><span>'+Math.round(influenceBoost()*100)+'% EFFICIENCY</span></div></div><div class="rack-visual"><i></i><i></i><i></i><i></i><b>H</b></div></div><div class="section-title"><div><small>PROCUREMENT</small><h2>Expand the network</h2></div><span>BUY QUANTITY</span></div><div class="seg machine-seg">'+qs.map(function(q){return '<button data-qty="'+q+'" class="'+(qty==q?'on':'')+'">'+q+'</button>'}).join('')+'</div>';HW.forEach(function(name,i){var c=qty==='MAX'?maxBuy(i):qty,cost=batch(i,Math.max(1,c)),lock=s.life<Math.pow(7,i)*35,owned=s.hw[i],rate=hwIncome(i)*owned*mile(owned),next=owned<10?10:owned<25?25:owned<50?50:owned<100?100:owned,pct=next===owned?100:owned/(next||1)*100;out+='<article class="machine-card '+(lock?'locked ':'')+'tier-'+(i%4)+'"><div class="machine-art"><div class="machine-screen"><i></i><i></i><i></i></div><span></span><b>'+iconFor(i)+'</b></div><div class="machine-info"><small>'+(['PERSONAL COMPUTE','RACK SYSTEM','FACILITY CLASS','FRONTIER TECH'][Math.min(3,Math.floor(i/6))])+'</small><h3>'+name+'</h3><div class="machine-stats"><span><b>'+owned+'</b> OWNED</span><span><b>£'+fmt(rate)+'</b> PER SEC</span></div><div class="milestone-track"><i style="width:'+Math.min(100,pct)+'%"></i></div><em>'+(owned>=100?'Maximum milestone active':'Next output doubling at '+next)+'</em></div><button class="machine-buy" data-buy="'+i+'" '+(lock||c<1||s.cash<cost?'disabled':'')+'><small>'+(lock?'REQUIRES £'+fmt(Math.pow(7,i)*35):'INSTALL '+c)+'</small><b>£'+fmt(cost)+'</b></button></article>'});return out+'</section>'}
function tokens(){var next=Math.min(TOK.length-1,s.token+1),out='<section class="view token-view"><div class="protocol-lab"><div class="lab-grid"></div><div class="active-orb token-'+(s.token%5)+'"><div class="orbit-ring"></div><div class="orb-core">'+TOK[s.token].charAt(0)+'</div><i></i><i></i></div><div class="lab-copy"><small>ACTIVE OUTPUT PROTOCOL</small><h1>'+TOK[s.token]+'</h1><p>Core output is <b>£'+fmt(baseTap())+'</b> per tap before streak bonuses.</p><div class="level-readout"><span>LEVEL '+s.tap+'</span><span>NEXT, '+TOK[next]+'</span></div><div class="lab-progress"><i style="width:'+Math.min(100,(s.tap%5)/5*100)+'%"></i></div></div></div><button id="buy10" class="install-protocol" '+(s.cash<tapCost(10)?'disabled':'')+'><span><small>ACCELERATE RESEARCH</small><b>Install 10 core levels</b></span><strong>£'+fmt(tapCost(10))+'</strong></button><div class="section-title"><div><small>PROTOCOL ARCHIVE</small><h2>Discovered cores</h2></div><span>'+(s.token+1)+' / '+TOK.length+'</span></div><div class="protocol-grid">';TOK.forEach(function(name,i){var lock=s.tap<i*5;out+='<article class="protocol-card '+(lock?'locked ':'')+(i===s.token?'active ':'')+'token-'+(i%5)+'"><div class="mini-orb"><i>'+name.charAt(0)+'</i></div><small>'+(lock?'ENCRYPTED':i===s.token?'RUNNING':'DISCOVERED')+'</small><h3>'+name+'</h3><p>+'+(2+i)+'% '+(i%2?'hardware':'tap')+' output</p><span>'+(lock?'LEVEL '+i*5:'PROTOCOL '+String(i+1).padStart(2,'0'))+'</span></article>'});return out+'</div></section>'}
function influence(){var jobs=[['Launch the Signal Podcast','Turn the founder story into weekly attention'],['Release Open Source Tools','Build a community that improves the network'],['Sponsor an Esports Team','Put Hash Empire in front of a global audience'],['Host the Future Summit','Own the conversation around frontier technology'],['Fund the Creator Network','Create a permanent distribution engine'],['Establish a Research Lab','Convert reputation into breakthrough technology']],funded=s.influence||[],boost=Math.round((influenceBoost()-1)*100),out='<section class="view influence-view"><div class="signal-hero"><div class="signal-map"><i></i><i></i><i></i><i></i><i></i><b>H</b></div><div><small>GLOBAL SIGNAL NETWORK</small><h1>'+fmt(Math.max(1,s.life/10))+' people reached</h1><p>Your reputation now adds <b>+'+boost+'%</b> to every source of income, permanently.</p></div></div><div class="influence-stats"><div><small>PROJECTS LIVE</small><b>'+funded.length+' / 6</b></div><div><small>PERMANENT BOOST</small><b>+'+boost+'%</b></div><div><small>STATUS</small><b>'+(!funded.length?'UNKNOWN':funded.length<3?'RISING':'GLOBAL')+'</b></div></div><div class="section-title"><div><small>CAMPAIGN BOARD</small><h2>Build public influence</h2></div><span>PERMANENT</span></div>';jobs.forEach(function(x,i){var cost=Math.pow(10,4+i*2.5),lock=s.life<cost/2,owned=funded.indexOf(i)>-1;out+='<article class="campaign-card campaign-'+i+' '+(lock?'locked ':'')+(owned?'funded':'')+'"><div class="campaign-number">0'+(i+1)+'</div><div class="campaign-art"><i></i><i></i><i></i><b>'+['◉','⌘','✦','△','◎','⌬'][i]+'</b></div><div class="campaign-copy"><small>'+(['MEDIA','COMMUNITY','CULTURE','EVENTS','CREATORS','RESEARCH'][i])+'</small><h3>'+x[0]+'</h3><p>'+x[1]+'</p><span>+'+(5+i*3)+'% ALL INCOME, FOREVER</span></div><button class="campaign-buy" data-fund="'+i+'" '+(lock||owned||s.cash<cost?'disabled':'')+'>'+(owned?'<small>PROJECT LIVE</small><b>ONLINE</b>':lock?'<small>LOCKED</small><b>£'+fmt(cost/2)+' lifetime</b>':'<small>FUND PROJECT</small><b>£'+fmt(cost)+'</b>')+'</button></article>'});return out+'</section>'}
function legacy(){var pts=Math.floor(Math.pow(s.life/1e9,.25)),mult=(1+s.legacy*.1).toFixed(1),out='<section class="view legacy-view"><div class="legacy-cosmos"><div class="cosmos-stars"></div><div class="legacy-core"><i></i><b>'+s.legacy+'</b></div><div class="legacy-copy"><small>EMPIRE MEMORY CORE</small><h1>Your legacy is x'+mult+'</h1><p>Every relaunch makes the next empire faster, stronger and slightly more inevitable.</p></div></div><div class="exit-panel"><div><small>EXIT OPPORTUNITY</small><h2>'+pts+' Legacy Point'+(pts===1?'':'s')+' available</h2><p>Cash, hardware, locations and tap levels reset. Influence, blueprints and Legacy survive.</p></div><button id="prestige" '+(pts<1?'disabled':'')+'>'+(pts<1?'<small>NEXT EXIT AT</small><b>£1B LIFETIME</b>':'<small>READY</small><b>EXIT AND RELAUNCH</b>')+'</button></div><div class="section-title"><div><small>PERMANENT VAULT</small><h2>Blueprint collection</h2></div><span>'+s.blue.length+' / '+BLUE.length+'</span></div><div class="blueprint-grid">';BLUE.forEach(function(name,i){var owned=s.blue.indexOf(i)>-1,rarity=['common','rare','epic','legendary'][Math.min(3,Math.floor(i/4))];out+='<article class="blueprint-tile '+rarity+' '+(!owned?'locked':'')+'"><div class="blueprint-art"><i></i><i></i><b>'+(['C','R','P','S','A','O'][i%6])+'</b></div><small>'+rarity.toUpperCase()+'</small><h3>'+name+'</h3><p>x'+(1.03+i*.01).toFixed(2)+' '+(['personal','rack','facility','frontier'][i%4])+'</p><span>'+(owned?'OWNED':'UNDISCOVERED')+'</span></article>'});out+='</div><div class="settings-panel"><div><small>EMPIRE SETTINGS</small><h2>Control room</h2></div><div class="setting"><span>Sound effects</span><button class="toggle '+(s.settings.sound?'on':'')+'" data-setting="sound"></button></div><div class="setting"><span>Haptic feedback</span><button class="toggle '+(s.settings.vibration?'on':'')+'" data-setting="vibration"></button></div><button id="reset" class="wide-button danger">RESET GAME DATA</button></div></section>';return out}
function screen(){if(tab==='Empire')return empire();if(tab==='Hardware')return hardware();if(tab==='Tokens')return tokens();if(tab==='Influence')return influence();return legacy()}
function render(){cancelAnimationFrame(raf);document.getElementById('app').innerHTML='<main class="shell">'+hud()+screen()+nav()+'</main>';bind();if(tab==='Empire')startScene();showTutorial()}
function bind(){
 document.querySelectorAll('[data-tab]').forEach(function(el){el.onclick=function(){tab=el.dataset.tab;if(tab==='Hardware'&&s.tutorial===3)s.tutorial=4;save();render()}});
 document.querySelectorAll('[data-qty]').forEach(function(el){el.onclick=function(){qty=el.dataset.qty==='MAX'?'MAX':Number(el.dataset.qty);render()}});
 document.querySelectorAll('[data-buy]').forEach(function(el){el.onclick=function(){var i=Number(el.dataset.buy),c=qty==='MAX'?maxBuy(i):qty,cost=batch(i,c);if(!c||s.cash<cost)return;var before=s.hw[i];s.cash-=cost;s.hw[i]+=c;if(i===0&&s.tutorial===4)s.tutorial=5;var hit=checkMilestone(i,before,s.hw[i]);ping(240);save();render();if(hit)showMilestone(i,hit);else hardwareArrival(i,c)}});
 document.querySelectorAll('[data-fund]').forEach(function(el){el.onclick=function(){var i=Number(el.dataset.fund),cost=Math.pow(10,4+i*2.5);if(s.cash>=cost&&(s.influence||[]).indexOf(i)<0){s.cash-=cost;s.influence.push(i);save();render();celebrate('Signal amplified','Influence project online','All income permanently increased by '+(5+i*3)+'%')}}});
 document.querySelectorAll('[data-setting]').forEach(function(el){el.onclick=function(){var k=el.dataset.setting;s.settings[k]=!s.settings[k];save();render()}});
 var mine=document.getElementById('mine');if(mine)mine.onpointerdown=doTap;
 var ai=document.getElementById('aiBubble');if(ai)ai.onclick=function(){reaction(['We are one surge protector away from greatness.','The landlord called. I pretended to be a printer.','I have calculated our odds. Surprisingly non-zero.','More hardware. Less sleep. Excellent.'][Math.floor(Math.random()*4)])};
 var claim=document.getElementById('claimMission');if(claim)claim.onclick=claimMission;
 var u=document.getElementById('upTap');if(u)u.onclick=function(){var c=tapCost(1);if(s.cash>=c){s.cash-=c;s.tap++;s.token=Math.min(TOK.length-1,Math.floor(s.tap/5));if(s.tutorial===2)s.tutorial=3;ping(420);save();render();toast('Output boosted to £'+fmt(baseTap())+' per tap')}};
 var b=document.getElementById('buy10');if(b)b.onclick=function(){var c=tapCost(10);if(s.cash>=c){s.cash-=c;s.tap+=10;s.token=Math.min(TOK.length-1,Math.floor(s.tap/5));ping(520);save();render()}};
 var ex=document.getElementById('expand');if(ex)ex.onclick=function(){var c=worldCost();if(s.cash>=c&&isFinite(c))locationTransition(c)};
 var p=document.getElementById('prestige');if(p)p.onclick=prestige;
 var r=document.getElementById('reset');if(r)r.onclick=function(){if(confirm('Reset all Hash Empire progress? This cannot be undone.')){s=fresh();save();render()}}
}
function doTap(e){e.preventDefault();var now=Date.now(),wasMax=combo>=7.95;combo=now-lastTap<520?Math.min(8,combo+.22):Math.max(1,combo);lastTap=now;if(combo>=7.95&&!wasMax){overclockUntil=now+8000;reaction('OVERCLOCK ONLINE. Try not to melt the walls.');toast('OVERCLOCK, double output for 8 seconds')}var critical=Math.random()<.075+combo*.006,v=tapVal()*(critical?5:1);s.cash+=v;s.life+=v;s.taps=(s.taps||0)+1;s.token=Math.min(TOK.length-1,Math.floor(s.tap/5));var tutorialAdvance=s.tutorial===1&&s.taps>=3;if(tutorialAdvance){s.tutorial=2;save()}if(s.settings.vibration&&navigator.vibrate)navigator.vibrate(critical?[18,25,18]:combo>5?14:7);ping(critical?360:170+combo*16);var core=document.getElementById('mine'),stageEl=document.getElementById('stage');core.classList.add('hit');if(critical){core.classList.add('critical');stageEl&&stageEl.classList.add('impact');setTimeout(function(){core&&core.classList.remove('critical');stageEl&&stageEl.classList.remove('impact')},330)}setTimeout(function(){core&&core.classList.remove('hit')},80);floater(e.clientX,e.clientY,(critical?'CRITICAL  ':'')+'+£'+fmt(v),critical);sparks(core,critical?15:7);updateHud();if(tutorialAdvance)setTimeout(function(){render();toast('Nice. Now upgrade your output.')},110)}
function updateHud(){var el=document.getElementById('cash');if(el)el.textContent='£'+fmt(s.cash);el=document.getElementById('income');if(el)el.textContent='+£'+fmt(income())+' / sec';el=document.getElementById('combo');if(el){el.textContent=(Date.now()<overclockUntil?'⚡ ':'')+'x'+combo.toFixed(1);el.className='combo-pill '+(combo>=5?'hot':'')}el=document.getElementById('combostat');if(el)el.textContent='x'+combo.toFixed(1);el=document.getElementById('tapstat');if(el)el.textContent='£'+fmt(baseTap());el=document.getElementById('powerbar');if(el)el.style.width=Math.min(100,combo/8*100)+'%';var stageEl=document.getElementById('stage');if(stageEl)stageEl.classList.toggle('overclock',Date.now()<overclockUntil);el=document.getElementById('missionbar');if(el)el.style.width=missionPct()+'%';var claim=document.getElementById('claimMission');if(claim&&(s.mission||0)<MISSIONS.length&&missionDone()){claim.disabled=false;claim.classList.add('ready');claim.querySelector('small').textContent='MISSION COMPLETE';claim.querySelector('em').textContent='CLAIM'}var up=document.getElementById('upTap');if(up)up.disabled=s.cash<tapCost(1);var expand=document.getElementById('expand');if(expand)expand.disabled=s.cash<worldCost()||!isFinite(worldCost());var buy10=document.getElementById('buy10');if(buy10)buy10.disabled=s.cash<tapCost(10);document.querySelectorAll('[data-buy]').forEach(function(btn){var i=Number(btn.dataset.buy),c=qty==='MAX'?maxBuy(i):qty;btn.disabled=s.life<Math.pow(7,i)*35||c<1||s.cash<batch(i,Math.max(1,c))});document.querySelectorAll('[data-fund]').forEach(function(btn){var i=Number(btn.dataset.fund),cost=Math.pow(10,4+i*2.5);btn.disabled=s.life<cost/2||(s.influence||[]).indexOf(i)>-1||s.cash<cost})}
function claimMission(){if((s.mission||0)>=MISSIONS.length||!missionDone())return;var m=activeMission();s.cash+=m.reward;s.life+=m.reward;s.mission=(s.mission||0)+1;if(s.mission===MISSIONS.length)s.chips+=5;ping(540);save();render();celebrate('Mission complete',m.title,'£'+fmt(m.reward)+' added to your empire')}
function checkMilestone(i,before,after){var hit=0;[10,25,50,100].forEach(function(n){var key=i+':'+n;if(before<n&&after>=n&&s.milestones.indexOf(key)<0){s.milestones.push(key);hit=n}});return hit}
function showMilestone(i,n){var bonus=hwIncome(i)*n*mile(n)*90;s.cash+=bonus;s.life+=bonus;if(n>=25&&s.blue.indexOf(i%BLUE.length)<0)s.blue.push(i%BLUE.length);save();celebrate(n+' owned',HW[i]+' milestone','Income doubled, plus £'+fmt(bonus)+' launch bonus')}
function celebrate(title,sub,copy){var m=document.createElement('div');m.className='modal celebration';m.innerHTML='<div class="modal-box"><div class="burst"><i></i><i></i><i></i><i></i><b>✦</b></div><small class="eyebrow">MOMENTUM UNLOCKED</small><h2>'+title+'</h2><h3>'+sub+'</h3><p>'+copy+'</p><button class="wide-button">KEEP BUILDING</button></div>';document.body.appendChild(m);m.querySelector('button').onclick=function(){ping(640);m.remove()}}
function showTutorial(){if(document.querySelector('.coach,.intro-modal')||s.tutorial>=5)return;if(s.tutorial===0){var m=document.createElement('div');m.className='modal intro-modal';m.innerHTML='<div class="modal-box intro-box"><div class="modal-mark">H</div><small class="eyebrow">CHAPTER ONE</small><h2>One laptop. One garage.</h2><p>You have £25, an ageing machine and a ridiculous amount of ambition. Generate your first hashes, invest the cash and turn this room into a technology empire.</p><button id="begin" class="wide-button">BOOT THE LAPTOP</button></div>';document.body.appendChild(m);m.querySelector('#begin').onclick=function(){s.tutorial=1;save();m.remove();showTutorial()};return}var data={1:['Tap the core','Generate three hashes to wake the machine.'],2:['Boost your output','You have enough cash. Buy your first tap upgrade.'],3:['Make money while away','Open Hardware from the navigation below.'],4:['Buy your first laptop','Install a Refurbished Laptop to start passive income.']}[s.tutorial];if(!data)return;var c=document.createElement('div');c.className='coach step'+s.tutorial;c.innerHTML='<small>GUIDED START</small><b>'+data[0]+'</b><span>'+data[1]+'</span>';document.querySelector('.shell').appendChild(c)}
function locationTransition(cost){var from=LOC[s.loc],to=LOC[s.loc+1],m=document.createElement('div');m.className='location-transition';m.innerHTML='<div class="travel-grid"></div><div class="travel-copy"><small>EMPIRE EXPANSION</small><h2>'+from+'</h2><div class="travel-line"><i></i></div><h2>'+to+'</h2><p>Packing the operation and rerouting the network...</p></div>';document.body.appendChild(m);ping(380);setTimeout(function(){s.cash-=cost;s.loc++;save();render();m.classList.add('arrived');m.querySelector('p').textContent='New operation online';ping(680)},1350);setTimeout(function(){m.remove();celebrate('New location',to,'More space, new hardware tiers and a much bigger ceiling.')},2350)}
function floater(x,y,text,critical){var f=document.createElement('i');f.className='floater'+(critical?' critical-floater':'');f.style.left=(x-20)+'px';f.style.top=(y-15)+'px';f.textContent=text;document.body.appendChild(f);setTimeout(function(){f.remove()},850)}
function sparks(core,count){if(!core||!s.settings.motion)return;var box=core.getBoundingClientRect();for(var i=0;i<(count||7);i++){var p=document.createElement('i'),a=Math.random()*Math.PI*2,d=35+Math.random()*(count>7?90:55);p.className='spark';p.style.left=(box.left+box.width/2)+'px';p.style.top=(box.top+box.height/2)+'px';p.style.setProperty('--dx',Math.cos(a)*d+'px');p.style.setProperty('--dy',Math.sin(a)*d+'px');p.style.background=count>7&&i%2?'#ffd76b':'#5af2e8';document.body.appendChild(p);setTimeout(function(x){return function(){x.remove()}}(p),650)}}
function reaction(text){var b=document.getElementById('aiBubble');if(!b)return;b.querySelector('span').textContent=text;b.classList.remove('talking');void b.offsetWidth;b.classList.add('talking')}
function hardwareArrival(i,count){var d=document.createElement('div');d.className='delivery-drop';d.innerHTML='<div class="delivery-crate"><i>H</i></div><div><small>DELIVERY INSTALLED</small><b>'+count+' × '+HW[i]+'</b><span>+£'+fmt(hwIncome(i)*count)+'/sec base output</span></div>';document.body.appendChild(d);reaction(['More machines. I will find another extension lead.','Installed. The room is now '+(7+i*9)+'% more impressive.','Hardware online. Passive income is the civilised option.'][i%3]);setTimeout(function(){d.classList.add('leave')},1800);setTimeout(function(){d.remove()},2300)}
function toast(text){var t=document.createElement('div');t.className='toast';t.textContent=text;document.body.appendChild(t);setTimeout(function(){t.remove()},2400)}
function ping(freq){if(!s.settings.sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();var o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*1.35,audio.currentTime+.06);g.gain.setValueAtTime(.025,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.08);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.08)}catch(e){}}
function prestige(){var pts=Math.floor(Math.pow(s.life/1e9,.25));if(pts<1)return;if(confirm('Exit this run for '+pts+' Legacy Point'+(pts===1?'':'s')+'? Cash, hardware, locations and tap upgrades will reset.')){var keep=s.legacy+pts,blue=s.blue,chips=s.chips,settings=s.settings,influence=s.influence;s=fresh();s.legacy=keep;s.blue=blue;s.chips=chips;s.settings=settings;s.influence=influence;save();render()}}
function startScene(){canvas=document.getElementById('world');if(!canvas)return;ctx=canvas.getContext('2d');sceneTime=0;drawScene()}
function drawScene(){if(!canvas||!document.body.contains(canvas))return;var d=Math.min(window.devicePixelRatio||1,2),w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==Math.round(w*d)||canvas.height!==Math.round(h*d)){canvas.width=Math.round(w*d);canvas.height=Math.round(h*d)}ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);sceneTime+=.012;if(s.loc===0){var assets=s.hw.reduce(function(a,b){return a+b},0),nodes=Math.min(12,Math.floor(assets/3));ctx.lineWidth=1;for(var nn=0;nn<nodes;nn++){var nx=w*.54+(nn%4)*w*.095,ny=h*.39+Math.floor(nn/4)*h*.07,pulse=.45+.35*Math.sin(sceneTime*5+nn);ctx.strokeStyle='rgba(83,238,224,'+pulse*.38+')';ctx.beginPath();ctx.moveTo(w*.5,h*.58);ctx.lineTo(nx,ny);ctx.stroke();ctx.fillStyle='rgba(94,247,231,'+pulse+')';ctx.shadowBlur=10;ctx.shadowColor='#59eadf';ctx.beginPath();ctx.arc(nx,ny,2.2,0,Math.PI*2);ctx.fill()}ctx.shadowBlur=0;raf=requestAnimationFrame(drawScene);return}var palettes=[['#071321','#101927','#05070c'],['#0a1820','#18252b','#05090c'],['#071a2b','#10213a','#05070f'],['#071f27','#12313a','#061014'],['#111328','#202342','#070812']],pal=palettes[Math.min(palettes.length-1,s.loc)]||palettes[0],sky=ctx.createLinearGradient(0,0,0,h);sky.addColorStop(0,pal[0]);sky.addColorStop(.55,pal[1]);sky.addColorStop(1,pal[2]);ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);
// rear wall and ceiling
ctx.fillStyle='#111a25';ctx.fillRect(0,0,w,h*.62);ctx.strokeStyle='#243341';ctx.lineWidth=1;for(var x=0;x<w;x+=64){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h*.62);ctx.stroke()}for(var y=40;y<h*.62;y+=52){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}
if(s.loc>0){ctx.fillStyle='#091016';ctx.fillRect(w*.3,18,w*.4,42);ctx.strokeStyle='#405563';ctx.strokeRect(w*.3,18,w*.4,42);ctx.fillStyle='#6feee3';ctx.globalAlpha=.68;ctx.font='700 11px Space Grotesk';ctx.textAlign='center';ctx.fillText(s.loc===1?'HASH INDUSTRIES  •  UNIT 01':LOC[s.loc].toUpperCase(),w*.5,43);ctx.textAlign='left';ctx.globalAlpha=1;ctx.fillStyle='#1b2930';ctx.fillRect(0,h*.08,w*.06,h*.5);ctx.fillRect(w*.94,h*.08,w*.06,h*.5);ctx.fillStyle='#34444b';ctx.fillRect(0,h*.1,w,h*.025)}
// cyan tube lights
ctx.shadowBlur=18;ctx.shadowColor='#4ce9e2';ctx.fillStyle='#78fff5';ctx.fillRect(w*.12,68,w*.19,3);ctx.fillRect(w*.69,68,w*.19,3);ctx.shadowBlur=0;ctx.fillStyle='#55e8df22';ctx.fillRect(w*.08,70,w*.27,h*.5);
// left desk and monitor
ctx.fillStyle='#080c12';ctx.fillRect(w*.05,h*.38,w*.28,h*.04);ctx.fillStyle='#172431';ctx.fillRect(w*.09,h*.25,w*.18,h*.13);ctx.strokeStyle='#3d6870';ctx.strokeRect(w*.09,h*.25,w*.18,h*.13);var mg=ctx.createLinearGradient(w*.1,h*.26,w*.25,h*.37);mg.addColorStop(0,'#1d5871');mg.addColorStop(1,'#12143c');ctx.fillStyle=mg;ctx.fillRect(w*.105,h*.265,w*.15,h*.095);ctx.strokeStyle='#64e9df80';for(var l=0;l<4;l++){ctx.beginPath();ctx.moveTo(w*.115,h*(.33-l*.012));ctx.lineTo(w*(.14+l*.025),h*(.29+l*.006));ctx.lineTo(w*(.18+l*.018),h*(.315-l*.008));ctx.lineTo(w*.245,h*(.28+l*.012));ctx.stroke()}ctx.fillStyle='#15202a';ctx.fillRect(w*.16,h*.38,4,h*.18);ctx.fillRect(w*.27,h*.38,4,h*.18);
// owned laptops spread across the workbench
var laptops=Math.min(5,s.hw[0]||0);for(var lp=0;lp<laptops;lp++){var lx=w*.045+lp*w*.055,ly=h*.395;ctx.fillStyle='#273847';ctx.beginPath();ctx.moveTo(lx,ly);ctx.lineTo(lx+19,ly);ctx.lineTo(lx+16,ly-11);ctx.lineTo(lx+3,ly-11);ctx.closePath();ctx.fill();ctx.fillStyle=lp%2?'#5ee9df':'#48aaff';ctx.globalAlpha=.55;ctx.fillRect(lx+5,ly-9,9,6);ctx.globalAlpha=1}
// custom desktops add a second illuminated workstation
if((s.hw[1]||0)>0){ctx.fillStyle='#0a0e14';ctx.fillRect(w*.35,h*.37,w*.2,h*.035);var screens=Math.min(3,s.hw[1]);for(var ds=0;ds<screens;ds++){var dx=w*.355+ds*w*.065;ctx.fillStyle='#172936';ctx.fillRect(dx,h*.285,w*.055,h*.08);ctx.strokeStyle='#4bded45f';ctx.strokeRect(dx,h*.285,w*.055,h*.08);ctx.fillStyle=ds%2?'#342367':'#124b5c';ctx.fillRect(dx+3,h*.293,w*.055-6,h*.061);ctx.fillStyle='#69f4e8';ctx.fillRect(dx+7,h*.303+Math.sin(sceneTime*3+ds)*4,w*.03,1)}ctx.fillStyle='#16222c';ctx.fillRect(w*.38,h*.4,4,h*.16);ctx.fillRect(w*.51,h*.4,4,h*.16)}
// GPU purchases create a pulsing open air bench
if((s.hw[2]||0)>0){var cards=Math.min(6,s.hw[2]);ctx.fillStyle='#111923';ctx.fillRect(w*.31,h*.47,w*.28,h*.035);for(var gp=0;gp<cards;gp++){var gx=w*.32+gp*w*.043;ctx.fillStyle='#203246';ctx.fillRect(gx,h*.425,w*.034,h*.045);ctx.strokeStyle='#6a7c91';ctx.strokeRect(gx,h*.425,w*.034,h*.045);ctx.fillStyle=gp%2?'#825fff':'#51e5d8';ctx.globalAlpha=.6+.25*Math.sin(sceneTime*5+gp);ctx.beginPath();ctx.arc(gx+w*.017,h*.447,w*.01,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}}
// boxed expansion stock makes later purchases feel physical
var crates=Math.min(4,Math.floor(((s.hw[0]||0)+(s.hw[1]||0))/5));for(var cr=0;cr<crates;cr++){var cx=18+cr*29,cy=h*.555-cr%2*19;ctx.fillStyle='#27301f';ctx.fillRect(cx,cy,27,19);ctx.strokeStyle='#65704b';ctx.strokeRect(cx,cy,27,19);ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+27,cy+19);ctx.stroke()}
// right server racks, count reflects ownership
var rackOwned=(s.hw[3]||0)+(s.hw[4]||0)+(s.hw[5]||0),racks=Math.max(1,Math.min(4,1+Math.floor(rackOwned/2)));for(var r=0;r<racks;r++){var rx=w-(r+1)*56;ctx.fillStyle='#0b1018';ctx.fillRect(rx,h*.2,45,h*.39);ctx.strokeStyle=rackOwned?'#476c76':'#334858';ctx.strokeRect(rx,h*.2,45,h*.39);for(var q=0;q<6;q++){ctx.fillStyle='#182735';ctx.fillRect(rx+5,h*.23+q*24,35,16);ctx.fillStyle=(Math.sin(sceneTime*5+q+r)>0?'#50ebd8':'#277f79');ctx.fillRect(rx+9,h*.26+q*24,3,2);ctx.fillStyle='#785bff';ctx.fillRect(rx+15,h*.26+q*24,2,2)}}
// floor perspective
ctx.fillStyle='#070b11';ctx.fillRect(0,h*.59,w,h*.41);ctx.strokeStyle='#263547';for(var px=-w;px<w*2;px+=52){ctx.beginPath();ctx.moveTo(w/2,h*.59);ctx.lineTo(px,h);ctx.stroke()}for(var py=h*.64;py<h;py+=38){ctx.beginPath();ctx.moveTo(0,py);ctx.lineTo(w,py);ctx.stroke()}
// centre cable glow
var glow=ctx.createRadialGradient(w/2,h*.72,4,w/2,h*.72,w*.28);glow.addColorStop(0,'#38e5d526');glow.addColorStop(1,'transparent');ctx.fillStyle=glow;ctx.fillRect(0,h*.48,w,h*.52);
// dust motes
for(var m=0;m<18;m++){var mx=(m*83+sceneTime*22*(m%3+1))%(w+20)-10,my=(m*47+Math.sin(sceneTime+m)*14)%(h*.65);ctx.globalAlpha=.15+(m%4)*.06;ctx.fillStyle=m%3?'#bde6ef':'#5ff1e5';ctx.fillRect(mx,my,1.3,1.3)}ctx.globalAlpha=1;raf=requestAnimationFrame(drawScene)}
function offline(){var secs=Math.max(0,Math.min((Date.now()-Number(s.last||Date.now()))/1000,14400)),reward=income()*secs*.5;if(secs<20||reward<=0){s.last=Date.now();save();render();return}s.cash+=reward;s.life+=reward;s.last=Date.now();save();render();var m=document.createElement('div');m.className='modal';m.innerHTML='<div class="modal-box"><div class="modal-mark">H</div><h2>Your empire stayed online</h2><p>The network kept generating while you were away, at 50% offline efficiency.</p><div class="reward"><small>OFFLINE REVENUE</small><b>£'+fmt(reward)+'</b></div><button class="wide-button" id="collect">COLLECT AND CONTINUE</button></div>';document.body.appendChild(m);m.querySelector('#collect').onclick=function(){ping(480);m.remove()}}
setInterval(function(){var inc=income()/5;s.cash+=inc;s.life+=inc;if(Date.now()-lastTap>2200)combo=Math.max(1,combo-.08);updateHud()},200);setInterval(save,5000);offline();
})();
